steps:
  # 1. Build the container image using the Dockerfile inside the server folder
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/nc-investment/backend:$COMMIT_SHA',
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/nc-investment/backend:latest',
      '-f', 'server/Dockerfile',
      'server'
    ]

  # 2. Push the built container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/nc-investment/backend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/nc-investment/backend:latest']

  # 3. Deploy the container to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nc-investment-backend'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nc-investment/backend:$COMMIT_SHA'
      - '--region'
      - 'asia-south1' # Deploys to Mumbai region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MONGODB_URI=mongodb+srv://janagoutam147_db_user:RqIbFSHG3aeNQO1v@cluster0.a7ejmcm.mongodb.net/nc_investment?appName=Cluster0,TZ=Asia/Kolkata'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nc-investment/backend:$COMMIT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nc-investment/backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY


